package com.bos.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-03-22T20:35:44.064+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.crm.com/", name = "CustomerService")
@XmlSeeAlso({})
public interface CustomerService {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.com/", className = "FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.com/", className = "FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findAll();

    @WebMethod
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.crm.com/", className = "FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.crm.com/", className = "FindDecidedzoneIdByAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String findDecidedzoneIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findListHasAssociation", targetNamespace = "http://service.crm.com/", className = "FindListHasAssociation")
    @ResponseWrapper(localName = "findListHasAssociationResponse", targetNamespace = "http://service.crm.com/", className = "FindListHasAssociationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findListHasAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "assoigncustomerstodecideczone", targetNamespace = "http://service.crm.com/", className = "Assoigncustomerstodecideczone")
    @ResponseWrapper(localName = "assoigncustomerstodecideczoneResponse", targetNamespace = "http://service.crm.com/", className = "AssoigncustomerstodecideczoneResponse")
    public void assoigncustomerstodecideczone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Integer> arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findListNotAssociation", targetNamespace = "http://service.crm.com/", className = "FindListNotAssociation")
    @ResponseWrapper(localName = "findListNotAssociationResponse", targetNamespace = "http://service.crm.com/", className = "FindListNotAssociationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findListNotAssociation();

    @WebMethod
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.com/", className = "FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.com/", className = "FindCustomerByTelephoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
