package com.bos.domain;
// Generated 2018-3-10 11:27:41 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Decidedzone generated by hbm2java
 */
@Entity
@Table(name = "decidedzone", catalog = "bos")
public class Decidedzone implements java.io.Serializable {

	private String id;
	private String name;
	private String staffId;

	public Decidedzone() {
	}

	public Decidedzone(String id) {
		this.id = id;
	}

	public Decidedzone(String id, String name, String staffId) {
		this.id = id;
		this.name = name;
		this.staffId = staffId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "staff_id", length = 32)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

}
