package com.bos.domain;
// Generated 2018-3-23 20:56:56 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RoleFunction generated by hbm2java
 */
@Entity
@Table(name = "role_function", catalog = "bos")
public class RoleFunction implements java.io.Serializable {

	private RoleFunctionId id;

	public RoleFunction() {
	}

	public RoleFunction(RoleFunctionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 32)),
			@AttributeOverride(name = "functionId", column = @Column(name = "function_id", nullable = false, length = 32)) })
	public RoleFunctionId getId() {
		return this.id;
	}

	public void setId(RoleFunctionId id) {
		this.id = id;
	}

}
