package com.bos.domain;
// Generated 2018-3-23 20:56:56 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleFunctionId generated by hbm2java
 */
@Embeddable
public class RoleFunctionId implements java.io.Serializable {

	private String roleId;
	private String functionId;

	public RoleFunctionId() {
	}

	public RoleFunctionId(String roleId, String functionId) {
		this.roleId = roleId;
		this.functionId = functionId;
	}

	@Column(name = "role_id", nullable = false, length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "function_id", nullable = false, length = 32)
	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleFunctionId))
			return false;
		RoleFunctionId castOther = (RoleFunctionId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getFunctionId() == castOther.getFunctionId())
						|| (this.getFunctionId() != null && castOther.getFunctionId() != null
								&& this.getFunctionId().equals(castOther.getFunctionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getFunctionId() == null ? 0 : this.getFunctionId().hashCode());
		return result;
	}

}
